name: Bug report
description: Create a report to help improve the project.
title: "[BUG]"
labels:
  - bug
assignees:
  - eliashaeussler
body:
  - type: input
    id: php-version
    attributes:
      label: PHP version
      description: What PHP version are you using?
      placeholder: 'e.g. 7.4.27'
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: What version of this package are you using?
      placeholder: 'e.g. 0.6.3'
    validations:
      required: true
  - type: dropdown
    id: application
    attributes:
      label: Application
      description: On which platform did the error occur?
      options:
        - Composer
        - Phar
        - PHIVE
        - Docker
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      placeholder: 'e.g. macOS 11.4'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If possible, describe steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
