name: CGL
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare workflow
    uses: eliashaeussler/.github/.github/workflows/pull-request.yaml@fdc23f43e6ba48018b997f552dd39f9944c17c86 # main

  cgl:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.continue == 'true'
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          # We use the minimum supported PHP version
          php-version: 8.2 # renovate-ignore
          ini-file: development
          tools: composer:v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: npm

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@5c2bcf28d7b060ef3c601d7b476d5430a7b46c27 #v4
      - name: Install Frontend dependencies
        run: npm ci

      # Perform checks
      - name: Perform Composer checks
        run: composer ci
        shell: bash
      - name: Perform npm checks
        run: npm run ci

      # Zizmor
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
