name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@b4023b28e2974ed4e7ec3ce4b9a4503c98369b3c # 0.1.1

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@b4023b28e2974ed4e7ec3ce4b9a4503c98369b3c # 0.1.1
    with:
      # We use the minimum supported PHP version
      php-version: 8.2 # renovate-ignore
      npm: true

  unit-tests:
    name: 'Unit tests (PHP ${{ matrix.php-version }}, ${{ matrix.os }} & ${{ matrix.dependencies }} dependencies)'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        dependencies: ["highest", "lowest"]
        os: ["Ubuntu"]
        include:
          - php-version: "8.5"
            dependencies: "highest"
            os: "macOS"
          - php-version: "8.5"
            dependencies: "highest"
            os: "Windows"

    uses: eliashaeussler/gha/.github/workflows/composer-tests.yaml@b4023b28e2974ed4e7ec3ce4b9a4503c98369b3c # 0.1.1
    with:
      php-version: ${{ matrix.php-version }}
      dependencies: ${{ matrix.dependencies }}
      os: ${{ matrix.os }}
      command: 'test:unit'

  e2e-tests:
    name: 'E2E tests'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    uses: eliashaeussler/gha/.github/workflows/composer-tests.yaml@b4023b28e2974ed4e7ec3ce4b9a4503c98369b3c # 0.1.1
    with:
      command: 'test:e2e'

  test-coverage:
    name: 'Test coverage'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    uses: eliashaeussler/gha/.github/workflows/composer-test-coverage.yaml@b4023b28e2974ed4e7ec3ce4b9a4503c98369b3c # 0.1.1
